### ISSUE TITLE
About "Common Blocks"

### ISSUE THREAD

**Issue by caryyu** [hilleer/vscode-yaml-plus-json#347]
# Scenario Case
YAML to JSON

# Description
The conversion will also convert common blocks into the JSON, for example:

Here's the original YAML

```yaml
defaults: &defaults
  foo: 1
  bar: 2
  baz: 3

production:
  <<: *defaults
  bar: overriden
  quz: 4
```

Output will be like:
```json
{
  "defaults": {
    "foo": 1,
    "bar": 2,
    "baz": 3
  },
  "production": {
    "foo": 1,
    "bar": "overriden",
    "baz": 3,
    "quz": 4
  }
}
```

So the expected output shouldn't have "defaults" in the JSON file, any idea for this?

Here's the expected one:

```json
{
  "production": {
    "foo": 1,
    "bar": "overriden",
    "baz": 3,
    "quz": 4
  }
}
```
