### ISSUE TITLE
Convert yaml with multiple 'objects' in the same file

### ISSUE THREAD

**Issue by macCesar** [hilleer/vscode-yaml-plus-json#44]
I'm not sure if this is a feature request or a bug report.

But **yaml-plus-json** can't convert files that contain multiple 'objects', 'blocks', or whatever they are called in the YAML universe!! :-)

Or is it a restriction of the YAML structure ?? Because another extension says that the file is correct, BUT.. A preview YAML extension can't show it.. Unless there is only one object in the file.

`Dimension.yml` file:
```yaml
--- 
name: Dimension
extends: Size
summary: A simple object consisting of the position and size measurements. Effectively combines <Size> and <Point> but ensures numeric x/y values.
since: "2.0.0"
description: |
  When a dimension is returned by the [rect](Titanium.UI.View.rect) property, `x` represents the
  view's left position, and `y` represents the view's top position.

  The [size](Titanium.UI.View.size) property returns a dimension object with `x` and `y` both set
  to 0.
properties:
  - name: x
    summary: The x-axis coordinate of the position. When returned by <Titanium.UI.View.rect> the position is relative to it's parent.
    type: Number

  - name: y
    summary: The y-axis coordinate of the position. When returned by <Titanium.UI.View.rect> the position is relative to it's parent.
    type: Number

---
name: DimensionWithAbsolutes
extends: Dimension
summary: An extension of <Dimension> where Android returns additional absolute X/Y values/properties for <Titanium.UI.View.rect>
properties:
  - name: absoluteX
    summary: The x-axis coordinate of the position relative to the main window.
    type: Number
    platforms: [android]

  - name: absoluteY
    summary: The y-axis coordinate of the position relative to the main window.
    type: Number
    platforms: [android]

```

**As you can see in the example code.. It contains two ( --- ) objects!!! And yaml-plus-json can't convert it!! :-(**

**Other than that.. IT IS A GREAT TOOL!! Thanks!!**
