### ISSUE TITLE
Can't convert YAML files with JSON objects that has no spaces...

### ISSUE THREAD

**Issue by macCesar** [hilleer/vscode-yaml-plus-json#45]
I'm new to YAML files.. So I'm sorry if some terms are incorrect.

In the following example, the `osver` object contains what I called a JSON object...

As you can see.. there is NO space between `ios:` and the open bracket.. `{`.. and the file won't be converted...

If I add the space between them.. The file IS converted without a problem...

```yaml
---
name: Titanium.UI.iOS.BlurView
summary: |
    A <Titanium.UI.iOS.BlurView> object gives you an easy way implement some complex visual effects.
    The blur effect is applied to every view the blur view is added to by default. You can also place the
    blur view above other views and all visible views layered under the blur view are blurred as well.

    For more information on BlurView, please refer to the official [Apple documentation](https://developer.apple.com/documentation/uikit/uivisualeffectview).
    Note: Apple introduced two new constants <Titanium.UI.iOS.BLUR_EFFECT_STYLE_REGULAR> and <Titanium.UI.iOS.BLUR_EFFECT_STYLE_PROMINENT> in
    iOS 10. These are internally mapped to <Titanium.UI.iOS.BLUR_EFFECT_STYLE_LIGHT> and <Titanium.UI.iOS.BLUR_EFFECT_STYLE_EXTRA_LIGHT>.
extends: Titanium.UI.View
platforms: [iphone, ipad, macos]
since: {iphone: "5.4.0", ipad: "5.4.0", macos: "9.2.0"}
osver: {ios:{min: "8.0"}}
properties:
  - name: effect
    summary: The effect you provide for the view.
    type: Number
    constants: Titanium.UI.iOS.BLUR_EFFECT_STYLE_*
    default: undefined (no effect is applied)
```
